"""Add fields to VehicleLog for advanced logging

Revision ID: a7549e6dcd3b
Revises: 
Create Date: 2025-07-08 23:06:14.393397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7549e6dcd3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    with op.batch_alter_table('vehicle_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_plate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_authorized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('is_authorized')
        batch_op.drop_column('direction')
        batch_op.drop_column('license_plate')

    op.create_table('activity_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('activity_log_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_log_pkey'))
    )
    # ### end Alembic commands ###
